### ISSUE TITLE
Multiple package managers on the same machine

### ISSUE THREAD

**Issue by Naheel-Azawy** [willeccles/cpm#7]
Hi, nice work done here. I didn't make a PR as I thought it would be better to discuss it first.

The first thing that came to my mind when I saw this is AUR. It would be pretty simple to add a wrapper over `yay` for example and put it before `pacman` so that it picks it up whenever it finds it. But, this wouldn't be always what the user wants. For example, I usually do `-Syu` from `pacman`. For AUR I update only specific packages from time to time.

Other stuff that came to my mind, things like `pip`, `npm`, or even `go get`. Also, for some users they might want `flatpak` or `snap`. I made something similar for my dotfiles [here](https://github.com/Naheel-Azawy/naheel-dotfiles/blob/master/scripts/ndots#L237) but it wasn't meant to be a package manager. Only an installer for my dots.

The point is, should we have a way to manually select the actual package manager here or that would be too much?

**Comment by willeccles** [comment]
I have considered this option. I think it would probably be an env var; something like `CPM_PM=xbps` or something. However, I'm not sure how to handle a system where one would actually want to use multiple package managers. I have run into an issue on my own system where I have a script called `apt` that is in PATH and pretends to be apt, but instead just lists the packages apt was trying to install and exits so that I can manually install them with xbps. The problem is that cpm will find that and assume I want to use apt, when in reality it's just a script meant to fool setup/build scripts that use apt to install packages. For me, just being able to set xbps only would be enough. This could also be useful to people who use things like bedrock, where they have multiple package managers but might only use one main one.

However, I'm not sure there's a good way to manage multiple functional package managers with one program. The purpose of cpm is to abstract away the package manager on your system, but the concept of having multiple usable package managers defeats its purpose in a way. The goal of cpm is to make one set of args for multiple package mangers, but if you have 2 installed (pacman and yay, for example), you'd have to have something like `cpm install --pm=yay` or something along those lines. This *un*abstracts the package manager.

Over all I would say it's more useful to use cpm for your primary package manager (which you should use the most) and keep the others separate. This seems like a use case that circumvents cpm's goal of hiding the package manager.

**Comment by Naheel-Azawy** [comment]
I was hesitating from the beginning because I had the feeling that this might mess it up. I just wanted a single interface to access all pms. I understand it's messy, but using a single pm is unfortunately too good to be true. But anyway, I think I agree with you for now. Let's keep cpm nice and clean.

**Comment by willeccles** [comment]
Thanks for understanding!
